//! Data types representing the structured callers report tree.

use crate::FunctionInfo;
use serde::Serialize;

use super::context::ContextLine;

/// A single location in a caller function where the target is invoked.
#[derive(Debug, Clone, Serialize)]
pub struct CallerSite {
    /// 1-based line number of the call expression.
    pub line: usize,
    /// 0-based column offset of the call expression.
    pub column: usize,
    /// Raw text of the source line containing the call.
    pub line_text: String,
    /// Optional surrounding source lines for display context.
    pub context_lines: Vec<ContextLine>,
}

/// A call site that could not be attributed to an enclosing function.
///
/// Two cases produce one of these:
/// - the call sits at module level (e.g. inside a `static` / `const` initializer
///   or a `lazy_static!` / `Once`-wrapped body), in which case `caller_kind` is
///   `module-level`;
/// - the call sits inside a function whose stable id is not present in the
///   project's function index (typically because the file failed to parse, the
///   function is generated by a `proc-macro` whose expansion the visitor does
///   not see, or the resolver bound the call site to an id that does not match
///   the indexed function), in which case `caller_kind` is `unmapped`.
///
/// Either way the user can still navigate to the call: the file/line/text
/// triplet is preserved so the report does not silently drop the location.
#[derive(Debug, Clone, Serialize)]
pub struct UnresolvedCallSite {
    /// Source file containing this call site.
    pub file_path: String,
    /// 1-based line number of the call expression.
    pub line: usize,
    /// 0-based column offset of the call expression.
    pub column: usize,
    /// Raw text of the source line containing the call.
    pub line_text: String,
    /// Display name of the enclosing function if the visitor recorded one,
    /// even though the resolver could not match it back to a known function.
    pub caller_name: Option<String>,
    /// Why the call site is unresolved: `module-level` or `unmapped`.
    pub caller_kind: &'static str,
}

/// A function that calls the target, together with the specific call sites it contributes.
#[derive(Debug, Clone, Serialize)]
pub struct CallerFunction {
    /// Metadata for the calling function.
    pub info: FunctionInfo,
    /// Total number of call sites this function contributes (may exceed `call_sites.len()` if
    /// results were capped).
    pub call_sites_total: usize,
    /// Detailed call-site records, sorted by line then column.
    pub call_sites: Vec<CallerSite>,
}

/// All callers for one resolved target function.
#[derive(Debug, Clone, Serialize)]
pub struct CallersMatch {
    /// Metadata for the target (callee) function.
    pub info: FunctionInfo,
    /// Total call-site count across all resolved callers.
    pub call_sites_total: usize,
    /// Number of call sites that could not be attributed to a known function.
    pub unresolved_call_sites: usize,
    /// Locations of every unresolved call site, preserved so the user can
    /// still navigate even when the resolver could not bind a caller function.
    /// The length of this list always equals `unresolved_call_sites`.
    #[serde(default)]
    pub unresolved_call_site_locations: Vec<UnresolvedCallSite>,
    /// Per-caller breakdown, sorted by file path then start line.
    pub callers: Vec<CallerFunction>,
}

/// Top-level result returned by `build_callers_report*`.
#[derive(Debug, Clone, Serialize)]
pub struct CallersReport {
    /// The original query string that was resolved.
    pub query: String,
    /// One entry per matching target function found for `query`.
    pub matches: Vec<CallersMatch>,
}
